


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."category" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying
);


ALTER TABLE "public"."category" OWNER TO "postgres";


ALTER TABLE "public"."category" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."category_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."level" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "number" integer NOT NULL,
    "label" "text",
    "id_world" integer NOT NULL
);


ALTER TABLE "public"."level" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."level_has_question" (
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_level" integer NOT NULL,
    "id_question" integer NOT NULL
);


ALTER TABLE "public"."level_has_question" OWNER TO "postgres";


ALTER TABLE "public"."level" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."level_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."option" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "label" character varying NOT NULL,
    "isCorrect" boolean DEFAULT false NOT NULL,
    "id_question" integer NOT NULL
);


ALTER TABLE "public"."option" OWNER TO "postgres";


ALTER TABLE "public"."option" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."option_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."question" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "title" character varying NOT NULL,
    "weight" integer DEFAULT 1000 NOT NULL,
    "id_category" integer DEFAULT 1 NOT NULL
);


ALTER TABLE "public"."question" OWNER TO "postgres";


ALTER TABLE "public"."question" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."question_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "email" character varying NOT NULL,
    "username" character varying NOT NULL,
    "password" character varying NOT NULL,
    "points" integer DEFAULT 0,
    "id_userImg" integer DEFAULT 1,
    "isAdmin" boolean DEFAULT false NOT NULL
);


ALTER TABLE "public"."user" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."userImgs" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "imgName" character varying NOT NULL
);


ALTER TABLE "public"."userImgs" OWNER TO "postgres";


ALTER TABLE "public"."userImgs" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."userImgs_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."user_has_level" (
    "id_user" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "id_level" integer NOT NULL,
    "max_points" integer DEFAULT 0 NOT NULL
);


ALTER TABLE "public"."user_has_level" OWNER TO "postgres";


ALTER TABLE "public"."user_has_level" ALTER COLUMN "id_user" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_has_level_id_user_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE "public"."user" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."user_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE TABLE IF NOT EXISTS "public"."world" (
    "id" integer NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"() NOT NULL,
    "name" character varying NOT NULL,
    "icon" "text" NOT NULL
);


ALTER TABLE "public"."world" OWNER TO "postgres";


ALTER TABLE "public"."world" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."world_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



ALTER TABLE ONLY "public"."category"
    ADD CONSTRAINT "category_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."level_has_question"
    ADD CONSTRAINT "level_has_question_pkey" PRIMARY KEY ("id_level", "id_question");



ALTER TABLE ONLY "public"."level"
    ADD CONSTRAINT "level_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."option"
    ADD CONSTRAINT "option_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."userImgs"
    ADD CONSTRAINT "userImgs_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_email_key" UNIQUE ("email");



ALTER TABLE ONLY "public"."user_has_level"
    ADD CONSTRAINT "user_has_level_pkey" PRIMARY KEY ("id_user", "id_level");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_username_key" UNIQUE ("username");



ALTER TABLE ONLY "public"."world"
    ADD CONSTRAINT "world_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."level_has_question"
    ADD CONSTRAINT "level_has_question_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id");



ALTER TABLE ONLY "public"."level_has_question"
    ADD CONSTRAINT "level_has_question_id_question_fkey" FOREIGN KEY ("id_question") REFERENCES "public"."question"("id");



ALTER TABLE ONLY "public"."level"
    ADD CONSTRAINT "level_id_world_fkey" FOREIGN KEY ("id_world") REFERENCES "public"."world"("id");



ALTER TABLE ONLY "public"."option"
    ADD CONSTRAINT "option_id_question_fkey" FOREIGN KEY ("id_question") REFERENCES "public"."question"("id");



ALTER TABLE ONLY "public"."question"
    ADD CONSTRAINT "question_id_category_fkey" FOREIGN KEY ("id_category") REFERENCES "public"."category"("id");



ALTER TABLE ONLY "public"."user_has_level"
    ADD CONSTRAINT "user_has_level_id_level_fkey" FOREIGN KEY ("id_level") REFERENCES "public"."level"("id");



ALTER TABLE ONLY "public"."user_has_level"
    ADD CONSTRAINT "user_has_level_id_user_fkey" FOREIGN KEY ("id_user") REFERENCES "public"."user"("id");



ALTER TABLE ONLY "public"."user"
    ADD CONSTRAINT "user_id_userImg_fkey" FOREIGN KEY ("id_userImg") REFERENCES "public"."userImgs"("id");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";


GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";
GRANT ALL ON SCHEMA "public" TO "prisma";








































































































































































GRANT ALL ON TABLE "public"."category" TO "anon";
GRANT ALL ON TABLE "public"."category" TO "authenticated";
GRANT ALL ON TABLE "public"."category" TO "service_role";
GRANT ALL ON TABLE "public"."category" TO "prisma";



GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."category_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."level" TO "anon";
GRANT ALL ON TABLE "public"."level" TO "authenticated";
GRANT ALL ON TABLE "public"."level" TO "service_role";
GRANT ALL ON TABLE "public"."level" TO "prisma";



GRANT ALL ON TABLE "public"."level_has_question" TO "anon";
GRANT ALL ON TABLE "public"."level_has_question" TO "authenticated";
GRANT ALL ON TABLE "public"."level_has_question" TO "service_role";
GRANT ALL ON TABLE "public"."level_has_question" TO "prisma";



GRANT ALL ON SEQUENCE "public"."level_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."level_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."level_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."level_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."option" TO "anon";
GRANT ALL ON TABLE "public"."option" TO "authenticated";
GRANT ALL ON TABLE "public"."option" TO "service_role";
GRANT ALL ON TABLE "public"."option" TO "prisma";



GRANT ALL ON SEQUENCE "public"."option_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."option_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."option_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."option_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."question" TO "anon";
GRANT ALL ON TABLE "public"."question" TO "authenticated";
GRANT ALL ON TABLE "public"."question" TO "service_role";
GRANT ALL ON TABLE "public"."question" TO "prisma";



GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."question_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."user" TO "anon";
GRANT ALL ON TABLE "public"."user" TO "authenticated";
GRANT ALL ON TABLE "public"."user" TO "service_role";
GRANT ALL ON TABLE "public"."user" TO "prisma";



GRANT ALL ON TABLE "public"."userImgs" TO "anon";
GRANT ALL ON TABLE "public"."userImgs" TO "authenticated";
GRANT ALL ON TABLE "public"."userImgs" TO "service_role";
GRANT ALL ON TABLE "public"."userImgs" TO "prisma";



GRANT ALL ON SEQUENCE "public"."userImgs_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."userImgs_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."userImgs_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."userImgs_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."user_has_level" TO "anon";
GRANT ALL ON TABLE "public"."user_has_level" TO "authenticated";
GRANT ALL ON TABLE "public"."user_has_level" TO "service_role";
GRANT ALL ON TABLE "public"."user_has_level" TO "prisma";



GRANT ALL ON SEQUENCE "public"."user_has_level_id_user_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_has_level_id_user_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_has_level_id_user_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."user_has_level_id_user_seq" TO "prisma";



GRANT ALL ON SEQUENCE "public"."user_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."user_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."user_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."user_id_seq" TO "prisma";



GRANT ALL ON TABLE "public"."world" TO "anon";
GRANT ALL ON TABLE "public"."world" TO "authenticated";
GRANT ALL ON TABLE "public"."world" TO "service_role";
GRANT ALL ON TABLE "public"."world" TO "prisma";



GRANT ALL ON SEQUENCE "public"."world_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."world_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."world_id_seq" TO "service_role";
GRANT ALL ON SEQUENCE "public"."world_id_seq" TO "prisma";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "prisma";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "prisma";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "prisma";































